### ISSUE TITLE
does not work from base conda env

### ISSUE THREAD

**Issue by andgineer** [andgineer/garmin-daily#4]
Works from the project venv but not from base conda
May be my base installation has old garminconnect?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/Caskroom/miniconda/base/bin/garmin-daily", line 8, in <module>
    sys.exit(main())
  File "/usr/local/Caskroom/miniconda/base/lib/python3.9/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/Caskroom/miniconda/base/lib/python3.9/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/Caskroom/miniconda/base/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/Caskroom/miniconda/base/lib/python3.9/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/usr/local/Caskroom/miniconda/base/lib/python3.9/site-packages/garmin_daily/google_sheet.py", line 136, in main
    add_rows_from_garmin(
  File "/usr/local/Caskroom/miniconda/base/lib/python3.9/site-packages/garmin_daily/google_sheet.py", line 162, in add_rows_from_garmin
    daily.login()
  File "/usr/local/Caskroom/miniconda/base/lib/python3.9/site-packages/garmin_daily/garmin_aggregations.py", line 392, in login
    self.api.login()
  File "/usr/local/Caskroom/miniconda/base/lib/python3.9/site-packages/garminconnect/__init__.py", line 249, in login
    return self.authenticate()
  File "/usr/local/Caskroom/miniconda/base/lib/python3.9/site-packages/garminconnect/__init__.py", line 369, in authenticate
    response = self.sso_rest_client.post(
  File "/usr/local/Caskroom/miniconda/base/lib/python3.9/site-packages/garminconnect/__init__.py", line 110, in post
    raise GarminConnectConnectionError(f"Forbidden url: {url}") from err
garminconnect.GarminConnectConnectionError: Forbidden url: https://sso.garmin.com/sso/signin

**Comment by andgineer** [comment]
with garminconnect==0.1.49
the same problem

**Comment by andgineer** [comment]
ok it works in conda env with python 3.10
garminconnect problem?

https://github.com/cyberjunky/python-garminconnect/issues/111

**Comment by andgineer** [comment]
checked with fresh miniconda base env
works
